export const MEMES_LIST_REQUEST = 'MEMES_LIST_REQUEST';
export const MEMES_LIST_SUCCESS = 'MEMES_LIST_SUCCESS';
export const MEMES_LIST_FAIL = 'MEMES_LIST_FAIL';

export const UPLOAD_MEM_REQUEST = 'UPLOAD_MEM_REQUEST';
export const UPLOAD_MEM_SUCCESS = 'UPLOAD_MEM_SUCCESS';
export const UPLOAD_MEM_FAIL = 'UPLOAD_MEM_FAIL';